name: Java CI with Maven

on:
  workflow_run:
    workflows: [ "YouTrack-Closed" ]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn -B package -DskipTests --file pom.xml


      - name: Docker Build and Push Action
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          directory: .
          dockerfile: 'Dockerfile.prod'
          pushImage: true
          image: damou/library-app-borrow
          tags: ${{ github.sha }}
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}